#!/usr/bin/bash

unset VERIFY_TOKEN
unset PAGE_ACCESS_TOKEN
unset OPEN_WEATHER_MAP_API_KEY
unset WORKSPACE_ID
unset IBM_USERNAME
unset IBM_PASSWORD
unset IBM_VERSION
unset SPEECH_USERNAME
unset SPEECH_PASSWORD
unset GOOGLE_SCOPES
unset CLIENT_SECRET_FILE
unset APPLICATION_NAME